### ISSUE TITLE
Command kurang lengkap 

### ISSUE THREAD

**Issue by ikbrath** [widiarrohman1234/widiarrohman1234.github.io#4]
<img width="194" alt="github widi ada yang salah" src="https://github.com/user-attachments/assets/1fe17fa5-50e7-43de-88ca-bc8af2476dce">

Kurang -d

**Comment by widiarrohman1234** [comment]
Halo @ikbrath,

Terima kasih atas laporan masalah yang Anda sampaikan. Masukan Anda sangat berharga dan telah memberikan kontribusi positif bagi kemajuan repository ini. Saya telah melakukan perbaikan terhadap perintah tersebut sesuai dengan yang Anda rekomendasikan. Terima kasih atas bantuan dan kerjasamanya.

Salam hormat,  
@widiarrohman1234
